// Code generated by protoc-gen-go. DO NOT EDIT.
// source: skyray.proto

/*
Package skyray is a generated protocol buffer package.

It is generated from these files:
	skyray.proto

It has these top-level messages:
	Command
	Response
*/
package skyray

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Command   string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Arguments []string `protobuf:"bytes,2,rep,name=arguments" json:"arguments,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Command) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Response struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "skyray.Command")
	proto.RegisterType((*Response)(nil), "skyray.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SkyrayService service

type SkyrayServiceClient interface {
	Connect(ctx context.Context, in *Command, opts ...grpc.CallOption) (SkyrayService_ConnectClient, error)
}

type skyrayServiceClient struct {
	cc *grpc.ClientConn
}

func NewSkyrayServiceClient(cc *grpc.ClientConn) SkyrayServiceClient {
	return &skyrayServiceClient{cc}
}

func (c *skyrayServiceClient) Connect(ctx context.Context, in *Command, opts ...grpc.CallOption) (SkyrayService_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SkyrayService_serviceDesc.Streams[0], c.cc, "/skyray.SkyrayService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &skyrayServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SkyrayService_ConnectClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type skyrayServiceConnectClient struct {
	grpc.ClientStream
}

func (x *skyrayServiceConnectClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SkyrayService service

type SkyrayServiceServer interface {
	Connect(*Command, SkyrayService_ConnectServer) error
}

func RegisterSkyrayServiceServer(s *grpc.Server, srv SkyrayServiceServer) {
	s.RegisterService(&_SkyrayService_serviceDesc, srv)
}

func _SkyrayService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Command)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkyrayServiceServer).Connect(m, &skyrayServiceConnectServer{stream})
}

type SkyrayService_ConnectServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type skyrayServiceConnectServer struct {
	grpc.ServerStream
}

func (x *skyrayServiceConnectServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _SkyrayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skyray.SkyrayService",
	HandlerType: (*SkyrayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SkyrayService_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "skyray.proto",
}

func init() { proto.RegisterFile("skyray.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0xae, 0x2c,
	0x4a, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x1c, 0xb9, 0xd8,
	0x9d, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0x21, 0x4c, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x86, 0x8b, 0x33, 0xb1, 0x28, 0xbd, 0x34, 0x37,
	0x35, 0xaf, 0xa4, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08, 0x21, 0xa0, 0xa4, 0xc4, 0xc5,
	0x11, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc6, 0xc5, 0x96, 0x5f, 0x5a, 0x52,
	0x50, 0x5a, 0x02, 0x36, 0x82, 0x27, 0x08, 0xca, 0x33, 0x72, 0xe4, 0xe2, 0x0d, 0x06, 0x5b, 0x18,
	0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0x00, 0xb2, 0x37, 0x2f, 0x2f, 0x35, 0xb9, 0x44,
	0x88, 0x5f, 0x0f, 0xea, 0x32, 0xa8, 0x43, 0xa4, 0x04, 0x60, 0x02, 0x30, 0x63, 0x95, 0x18, 0x0c,
	0x18, 0x93, 0xd8, 0xc0, 0x0e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x53, 0xdc, 0x45,
	0xc8, 0x00, 0x00, 0x00,
}
